name: flutter_movie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  floor: ^1.4.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2
  mockito: ^5.0.17
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/movies/
    - assets/images/dash.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/dash.jpg"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/dash.jpg"
  adaptive_icon_background: "#000000"
  background_color: null

flutter_native_splash:
  color: "#000000"
  image: "assets/images/dash.jpg"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

